on:
  schedule:
  - cron: '*/5 * * * *'
env:
  AUTOUPDATE_COMMITTER_EMAIL: github-actions[scoop-autoupdate-bot]@users.noreply.github.com
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavator
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: ${{ env.AUTOUPDATE_COMMITTER_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.SCOOP_AUTOUPDATE_TOKEN }}
        SKIP_UPDATED: '1'
    # Checkout the repo again and check if new version was just commited
    # If Excavator just commited, it has no tag, dispatch to tagger
    - uses: actions/checkout@main
      with:
        ref: 'main'
    - name: Get current commit author
      id: getcommiter
      run: |
        echo ::set-output name=email::$(git show -s --format='%ae' refs/heads/main)
    outputs:
      git-commiter-email: ${{ steps.getcommiter.outputs.email }}

  update-tag:
    name: Update git tag
    needs: excavate
    runs-on: ubuntu-latest
    if: ${{ needs.excavate.outputs.git-commiter-email == env.AUTOUPDATE_COMMITTER_EMAIL }}
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      continue-on-error: true
      with:
        strip_v: false
    - name: Repository Dispatch
      if: steps.tag.outcome != 'success' # https://stackoverflow.com/a/58003436
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.SCOOP_AUTOUPDATE_TOKEN }}
        event-type: schedule-run
